name: Flutter Build
on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest  # Android 构建使用 Linux 服务器即可
    steps:
      - uses: actions/checkout@v4  # 拉取你的代码

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 使用稳定版

      - name: Install dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
