name: maibot_android
description: MaiBot Android App
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.4.0+140
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # pub repo
  intl: ^0.20.2
  async: ^2.11.0
  dio: ^5.7.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  device_info_plus: ^13.1.0
  package_info_plus: ^10.1.0
  path: ^1.9.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.10.0
  permission_handler: ^13.0.0
  http: ^1.2.2
  url_launcher: ^6.3.1
  file_picker: ^12.0.0-beta.5
  flutter_markdown: ^0.7.4+3
  toml: ^0.18.0
  archive: ^4.0.0
  ffi: ^2.1.2

  # get repo
  xterm: ^4.0.0
  settings:
    path: ./packages/settings
  global_repository:
    path: ./packages/global_repository
  shizuku_api: ^1.2.2
  dynamic_color: ^1.9.0

dependency_overrides:
  xterm:
    path: ./packages/xterm.dart
  global_repository:
    path: ./packages/global_repository
  settings:
    path: ./packages/settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
